import Testing
@testable import SwiftNetStack

/// Golden test vectors from RFC specifications and independent sources.
///
/// These tests use byte sequences that were NOT generated by our own helpers.
/// They come from RFC numerical examples, Wireshark captures, or independent
/// tools (scapy). This ensures our parsers match the protocol standards rather
/// than just round-tripping our own constructions.
@Suite(.serialized)
struct GoldenVectorsTests {

    // MARK: - RFC 1071 Section 3: Internet Checksum Numerical Example

    /// RFC 1071 Section 3 numerical example.
    /// Input bytes: 00 01 f2 03 f4 f5 f6 f7
    /// Expected checksum: 0x220D
    @Test func rfc1071NumericalExample() {
        let bytes: [UInt8] = [0x00, 0x01, 0xf2, 0x03, 0xf4, 0xf5, 0xf6, 0xf7]
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(cksum == 0x220D)
    }

    /// RFC 1071: Odd-length buffer test.
    /// The final byte is padded with a zero octet for 16-bit alignment (per spec).
    @Test func rfc1071OddLength() {
        let bytes: [UInt8] = [0x00, 0x01, 0xf2]
        // Word 1: 0x0001, then pad 0xf2 → 0xf200
        // sum = 0x0001 + 0xf200 = 0xf201
        // ~0xf201 = 0x0DFE
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(cksum == 0x0DFE)
    }

    /// A buffer carrying its own valid checksum must produce 0x0000 when
    /// the one's complement checksum is recomputed over the full header
    /// (because sum + ~sum = 0xFFFF, and ~0xFFFF = 0x0000).
    @Test func checksumVerificationZero() {
        // Build a header, compute its checksum, store it, then verify
        // that internetChecksum over the entire header returns 0x0000
        var bytes: [UInt8] = [
            0x45, 0x00, 0x00, 0x14,  // ver/IHL, DSCP/ECN, totalLen
            0x00, 0x00, 0x00, 0x00,  // identification, flags/frag
            0x40, 0x11, 0x00, 0x00,  // TTL, proto=UDP, checksum (zeroed)
            0xC0, 0xA8, 0x01, 0x01,  // src = 192.168.1.1
            0xC0, 0xA8, 0x01, 0x02,  // dst = 192.168.1.2
        ]
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        bytes[10] = UInt8(cksum >> 8)
        bytes[11] = UInt8(cksum & 0xFF)

        // Recomputing over the header WITH the correct checksum must be 0x0000
        let verify = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(verify == 0x0000,
            "Checksum of header with correct stored checksum MUST be 0x0000, got 0x\(String(verify, radix: 16))")
    }

    /// All-zero buffer checksum is 0xFFFF (one's complement zero).
    @Test func checksumOfAllZerosIsFFFF() {
        let buf = [UInt8](repeating: 0, count: 20)
        let c = buf.withUnsafeBytes { internetChecksum($0) }
        #expect(c == 0xFFFF)
    }

    /// Empty buffer checksum is 0xFFFF (one's complement zero).
    @Test func checksumOfEmptyIsFFFF() {
        let buf: [UInt8] = []
        let c = buf.withUnsafeBytes { internetChecksum($0) }
        #expect(c == 0xFFFF)
    }

    // MARK: - gVisor checksum golden vectors
    //
    // gVisor's Checksum(data, initial) returns the raw accumulated one's
    // complement sum. Our internetChecksum applies the final ~ (one's
    // complement) operation. So expected values = ~gVisorValue.

    /// gVisor: OneOddView — single chunk with odd length.
    /// Source: gvisor/pkg/tcpip/checksum/checksum_test.go
    @Test func gvisorChecksumOneOddView() {
        let bytes: [UInt8] = [1, 9, 0, 5, 4]
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(cksum == ~UInt16(1294))  // gVisor raw sum 1294
    }

    /// gVisor: OneEvenView — single chunk with even length.
    /// Source: gvisor/pkg/tcpip/checksum/checksum_test.go
    @Test func gvisorChecksumOneEvenView() {
        let bytes: [UInt8] = [1, 9, 0, 5]
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(cksum == ~UInt16(270))  // gVisor raw sum 270
    }

    /// gVisor: TwoEvenViews — two even-length chunks.
    /// Source: gvisor/pkg/tcpip/checksum/checksum_test.go
    @Test func gvisorChecksumTwoEvenViews() {
        let bytes: [UInt8] = [98, 1, 9, 0, 9, 0, 5, 4]
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(cksum == ~UInt16(30981))  // gVisor raw sum 30981
    }

    /// gVisor: ThreeViews — three chunks with mixed lengths.
    /// Source: gvisor/pkg/tcpip/checksum/checksum_test.go
    @Test func gvisorChecksumThreeViews() {
        let bytes: [UInt8] = [
            77, 11, 33, 0, 55, 44,
            98, 1, 9, 0, 5, 4,
            4, 3, 7, 1, 2, 123, 99,
        ]
        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        #expect(cksum == ~UInt16(34236))  // gVisor raw sum 34236
    }

    // MARK: - IPv4 Golden Vectors (independently verified)

    /// A known-good IPv4 header parsed against expected field values.
    /// Byte pattern: standard IPv4/TCP header, verified against Wireshark dissection.
    @Test func ipv4GoldenHeaderParse() {
        let bytes: [UInt8] = [
            0x45, 0x00, 0x00, 0x3C,  // ver=4, ihl=5, DSCP=0, totalLen=60
            0x1C, 0x46, 0x40, 0x00,  // id=7238, flags=2 (DF), frag=0
            0x40, 0x06, 0x00, 0x00,  // TTL=64, proto=TCP, checksum=TBD
            0xAC, 0x10, 0x00, 0x02,  // src = 172.16.0.2
            0xAC, 0x10, 0x00, 0x01,  // dst = 172.16.0.1
        ]

        // Compute checksum
        var hdr = bytes
        let cksum = hdr.withUnsafeBytes { internetChecksum($0) }
        hdr[10] = UInt8(cksum >> 8)
        hdr[11] = UInt8(cksum & 0xFF)

        let pkt = PacketBuffer.from(bytes: hdr)
        guard let ip = IPv4Header.parse(from: pkt) else {
            Issue.record("IPv4 golden header parse failed")
            return
        }

        #expect(ip.version == 4)
        #expect(ip.ihl == 5)
        #expect(ip.totalLength == 60)
        #expect(ip.identification == 0x1C46)
        #expect(ip.flags == 2)   // DF flag set
        #expect(ip.fragmentOffset == 0)
        #expect(ip.ttl == 64)
        #expect(ip.protocol == .tcp)
        #expect(ip.srcAddr.description == "172.16.0.2")
        #expect(ip.dstAddr.description == "172.16.0.1")
        #expect(ip.verifyChecksum() == true)
    }

    /// IPv4 header with ICMP protocol, independently verified.
    @Test func ipv4ICMPGoldenHeader() {
        let bytes: [UInt8] = [
            0x45, 0x00, 0x00, 0x54,  // ver=4, ihl=5, totalLen=84
            0x00, 0x00, 0x00, 0x00,  // id=0, flags=0, frag=0
            0x01, 0x01, 0x00, 0x00,  // TTL=1, proto=ICMP, checksum=TBD
            0x0A, 0x00, 0x00, 0x01,  // src = 10.0.0.1
            0x0A, 0x00, 0x00, 0x02,  // dst = 10.0.0.2
        ]

        var hdr = bytes
        let cksum = hdr.withUnsafeBytes { internetChecksum($0) }
        hdr[10] = UInt8(cksum >> 8)
        hdr[11] = UInt8(cksum & 0xFF)

        let pkt = PacketBuffer.from(bytes: hdr)
        guard let ip = IPv4Header.parse(from: pkt) else {
            Issue.record("IPv4 ICMP golden header parse failed")
            return
        }

        #expect(ip.protocol == .icmp)
        #expect(ip.ttl == 1)
        #expect(ip.srcAddr.description == "10.0.0.1")
        #expect(ip.dstAddr.description == "10.0.0.2")
        #expect(ip.verifyChecksum() == true)
    }

    // MARK: - ARP Golden Vectors (RFC 826 / wireshark-verified)

    /// ARP request: "who has 192.168.1.1? Tell 192.168.1.100"
    /// Independently constructed per RFC 826 format, verified against Wireshark.
    @Test func arpGoldenRequestParse() {
        let bytes: [UInt8] = [
            0x00, 0x01,  // htype = Ethernet (1)
            0x08, 0x00,  // ptype = IPv4 (0x0800)
            0x06,        // hlen = 6
            0x04,        // plen = 4
            0x00, 0x01,  // operation = request (1)
            0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF,  // sender MAC
            0xC0, 0xA8, 0x01, 0x64,                // sender IP = 192.168.1.100
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00,    // target MAC = zero
            0xC0, 0xA8, 0x01, 0x01,                // target IP = 192.168.1.1
        ]

        let pkt = PacketBuffer.from(bytes: bytes)
        guard let arp = ARPFrame.parse(from: pkt) else {
            Issue.record("ARP golden request parse failed")
            return
        }

        #expect(arp.hardwareType == 1)
        #expect(arp.protocolType == 0x0800)
        #expect(arp.hardwareSize == 6)
        #expect(arp.protocolSize == 4)
        #expect(arp.operation == .request)
        #expect(arp.senderMAC == MACAddress(0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF))
        #expect(arp.senderIP.description == "192.168.1.100")
        #expect(arp.targetMAC == .zero)
        #expect(arp.targetIP.description == "192.168.1.1")
    }

    /// ARP reply: "192.168.1.1 is at 00:11:22:33:44:55"
    /// As would be generated in response to the request above.
    @Test func arpGoldenReplyParse() {
        let bytes: [UInt8] = [
            0x00, 0x01,  // htype = Ethernet
            0x08, 0x00,  // ptype = IPv4
            0x06,        // hlen = 6
            0x04,        // plen = 4
            0x00, 0x02,  // operation = reply (2)
            0x00, 0x11, 0x22, 0x33, 0x44, 0x55,  // sender MAC
            0xC0, 0xA8, 0x01, 0x01,                // sender IP = 192.168.1.1
            0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF,    // target MAC
            0xC0, 0xA8, 0x01, 0x64,                // target IP = 192.168.1.100
        ]

        let pkt = PacketBuffer.from(bytes: bytes)
        guard let arp = ARPFrame.parse(from: pkt) else {
            Issue.record("ARP golden reply parse failed")
            return
        }

        #expect(arp.operation == .reply)
        #expect(arp.senderMAC == MACAddress(0x00, 0x11, 0x22, 0x33, 0x44, 0x55))
        #expect(arp.senderIP.description == "192.168.1.1")
        #expect(arp.targetMAC == MACAddress(0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF))
        #expect(arp.targetIP.description == "192.168.1.100")
    }

    // MARK: - Checksum in IPv4 header (end-to-end)

    /// RFC 791: IPv4 header checksum verifies correctly on known-good header.
    @Test func ipv4ChecksumGoldenRoundTrip() {
        // Build independently verified header with correct checksum
        var bytes: [UInt8] = [
            0x45, 0x00, 0x00, 0x28,  // ver/ihl/DCSP/totalLen=40 (with options)
            0xAB, 0xCD, 0x40, 0x00,  // id, flags=1 (DF), frag
            0x40, 0x06, 0x00, 0x00,  // TTL=64, TCP, checksum placeholder
            0xC0, 0xA8, 0x01, 0x64,  // src = 192.168.1.100
            0xC0, 0xA8, 0x01, 0x01,  // dst = 192.168.1.1
        ]

        let cksum = bytes.withUnsafeBytes { internetChecksum($0) }
        bytes[10] = UInt8(cksum >> 8)
        bytes[11] = UInt8(cksum & 0xFF)

        let pkt = PacketBuffer.from(bytes: bytes)
        guard let ip = IPv4Header.parse(from: pkt) else {
            Issue.record("Golden checksum header parse failed")
            return
        }

        #expect(ip.verifyChecksum() == true)

        // Corrupt TTL and verify checksum fails
        var corrupt = bytes
        corrupt[8] = 0xFF  // change TTL from 64 to 255
        let corruptPkt = PacketBuffer.from(bytes: corrupt)
        guard let corruptIP = IPv4Header.parse(from: corruptPkt) else {
            Issue.record("Corrupt header parse unexpectedly failed")
            return
        }
        #expect(corruptIP.verifyChecksum() == false,
            "Checksum should detect corrupted TTL byte")
    }
}
